import { Link } from 'react-router-dom'
import { Box, Button, Container, Stack, Typography } from '@mui/material'
import { ArrowForward, AutoAwesomeOutlined, LocalShippingOutlined, RecyclingOutlined } from '@mui/icons-material'
import { categories, products, promotions, siteContent, testimonials } from '../data'
import { ProductCard } from '../components/catalogue/ProductCard'
import { LeadCapture } from '../components/marketing/LeadCapture'

export function HomePage() {
  return <>
    <Box><Container><Box sx={{ minHeight: { xs: 560, md: 650 }, display: 'flex', alignItems: 'center', position: 'relative', py: 8 }}><Box sx={{ width: { xs: '100%', md: '54%' }, zIndex: 1 }}><Typography variant="overline" color="secondary.main">{promotions.heroEyebrow}</Typography><Typography variant="h1" sx={{ mt: 2, mb: 3, maxWidth: 600 }}>{siteContent.heroTitle}</Typography><Typography variant="h6" color="text.secondary" sx={{ maxWidth: 470, fontWeight: 400, lineHeight: 1.6 }}>{siteContent.heroCopy}</Typography><Button component={Link} to="/catalogue" variant="contained" size="large" endIcon={<ArrowForward />} sx={{ mt: 5 }}>Explore the collection</Button></Box><Box component="img" src="https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=85" alt="Gold jewelry arranged on a sculptural surface" sx={{ position: 'absolute', right: { xs: -40, md: -80 }, top: { xs: 90, md: 38 }, width: { xs: '78%', md: '53%' }, height: { xs: 420, md: 570 }, objectFit: 'cover', opacity: { xs: .24, md: 1 }, filter: { xs: 'saturate(.6)', md: 'none' } }} /></Box></Container></Box>
    <Container sx={{ py: 10 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'end' }} spacing={2} sx={{ mb: 5 }}><Box><Typography variant="overline" color="secondary.main">Curated for you</Typography><Typography variant="h2" sx={{ mt: 1 }}>The edit</Typography></Box><Button component={Link} to="/catalogue" endIcon={<ArrowForward />}>View all pieces</Button></Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(3, 1fr)' }, gap: { xs: 3, md: 4 } }}>{products.filter((product) => product.featured).map((product) => <ProductCard key={product.id} product={product} />)}</Box></Container>
    <Box sx={{ bgcolor: 'primary.light', py: 10 }}><Container><Typography variant="overline" color="secondary.main">Find your finish</Typography><Typography variant="h2" sx={{ mt: 1, mb: 5 }}>Shop by feeling</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' }, gap: 3 }}>{categories.map((category) => <Box component={Link} to={`/catalogue?category=${category.name}`} key={category.name} sx={{ textDecoration: 'none', color: 'inherit' }}><Box component="img" src={category.image} alt="" sx={{ width: '100%', aspectRatio: '1 / 1', objectFit: 'cover', display: 'block' }} /><Stack direction="row" justifyContent="space-between" sx={{ py: 2 }}><Box><Typography fontWeight={700}>{category.name}</Typography><Typography variant="body2" color="text.secondary">{category.count}</Typography></Box><ArrowForward /></Stack></Box>)}</Box></Container></Box>
    <Container sx={{ py: 11 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={{ xs: 6, md: 12 }}><Box sx={{ flex: 1 }}><Typography variant="overline" color="secondary.main">Why Ziva</Typography><Typography variant="h2" sx={{ mt: 1, maxWidth: 420 }}>Good jewelry, made thoughtfully.</Typography></Box><Box sx={{ flex: 1, display: 'grid', gap: 3 }}><Stack direction="row" spacing={2}><AutoAwesomeOutlined color="secondary" /><Box><Typography fontWeight={700}>Small-batch design</Typography><Typography color="text.secondary">Quietly distinctive pieces, released with intention.</Typography></Box></Stack><Stack direction="row" spacing={2}><RecyclingOutlined color="secondary" /><Box><Typography fontWeight={700}>Considered materials</Typography><Typography color="text.secondary">Recycled and responsible materials wherever possible.</Typography></Box></Stack><Stack direction="row" spacing={2}><LocalShippingOutlined color="secondary" /><Box><Typography fontWeight={700}>Easy gifting</Typography><Typography color="text.secondary">Thoughtful packaging and complimentary shipping over ₹8,000.</Typography></Box></Stack></Box></Stack></Container>
    <Box sx={{ bgcolor: '#e7dfd3', py: 9 }}><Container><Typography variant="overline" color="secondary.main">Kind words</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 5, mt: 4 }}>{testimonials.map((item) => <Box key={item.name}><Typography variant="h6" sx={{ lineHeight: 1.5, fontWeight: 400 }}>&ldquo;{item.quote}&rdquo;</Typography><Typography variant="body2" sx={{ mt: 2, fontWeight: 700 }}>{item.name} <Typography component="span" color="text.secondary"> / {item.role}</Typography></Typography></Box>)}</Box></Container></Box>
    <LeadCapture />
  </>
}
